pageinfo = [[1449974007,0,11,0,null],
	[1449974007,0,0,0,null],
	[1449974140,0,0,0,null],
	[1449974122,0,0,0,null],
	[1449974133,0,0,0,null],
	[1449974007,0,0,0,null],
	[1449974015,0,0,0,null],
	[1449974022,0,0,0,null],
	[1449974082,0,0,0,null],
	[1449974007,0,0,0,null],
	[1449974076,0,0,0,null],
	[1449974099,0,0,0,null],
	[1449974061,0,0,0,null],
	[1449974068,0,0,0,null],
	[1449974146,0,0,0,null],
	[1449974007,0,0,0,null]];
pagedata = [ ["http://techlav.ncat.edu/","TECHLAV","Autonomous Control &#38; Information Technology Institute North Carolina A &#38; T State Universty Home Thrusts Modeling and Analysis Resilient Control an...",""],
["http://techlav.ncat.edu/index.html","TECHLAV","Autonomous Control &#38; Information Technology Institute North Carolina A &#38; T State Universty Home Thrusts Modeling and Analysis Resilient Control an...",""],
["http://techlav.ncat.edu/thrust_one.html","Thrust 1 - TECHLAV","Lead: Dr. M. Jamshidi, UTSA People: Drs. J.J. Prevost, Mr. P. Benavidez, UTSA; Dr. A. Karimoddini N.C. A&#38;T Goal: Research Thrust 1 will develop sc...",""],
["http://techlav.ncat.edu/thrust_two.html","Thrust 2 - TECHLAV","Lead: Dr. A. Karimoddini, N.C. A&#38;T People: Drs. A. Karimoddini, S. Yi, N.C. A&#38;T; Drs. M. Jamshidi and B. Kelley, UTSA Research Thrust 2 will devel...",""],
["http://techlav.ncat.edu/thrust_three.html","Thrust 3 - TECHLAV","Lead: Dr. Y. Seong, N.C. A&#38;T People: Drs. A. Homaifar, A. Karimoddini, and J. Stephens, N.C. A&#38;T Goal: Research Thrust 3 will develop and provide ...",""],
["http://techlav.ncat.edu/edu_outreach.html","Educaiton &#38; Outreach - TECHLAV","Lead: Dr. J. Kelly, NC A&#38;T; Dr. N. Vadiee, SIPI Goal: TECHLAV promotes a diverse, productive, and prepared workforce with more STEM graduates acro...",""],
["http://techlav.ncat.edu/faculty_staff.html","Faculty &#38; Staff - TECHLAV","Director Abdollah (Ebbie) Homaifar Duke Energy Eminent Professor Director, Autonomous Control Information Technology Institute (ACIT) Department o...",""],
["http://techlav.ncat.edu/grad_students.html","Graduate Students - TECHLAV","Coming Soon . . . ",""],
["http://techlav.ncat.edu/scholars.html","TECHLAV Scholars - TECHLAV","Coming Soon . . . ",""],
["http://techlav.ncat.edu/advisory_board.html","Advisory Board - TECHLAV","Dr. Edward Tunstel is a senior roboticist in the Research &#38; Exploratory Development Department of JHU/APL. He has served as space robotics &#38; auton...",""],
["http://techlav.ncat.edu/publications.html","Publications - TECHLAV","A. Karimoddini, M. Karimadini, H. Lin, L. Shamgah, A. Homaifar, \"Development of a Decentralized Cooperative Control Technique for Collision Avoida...",""],
["http://techlav.ncat.edu/seminars.html","Seminars - TECHLAV","TECHLAV Seminar Series",""],
["http://techlav.ncat.edu/news.html","News - TECHLAV","October 9, 2015: Dr. Homaifar met with Ms. Jasmine Spencer from Fox 8 news to discuss our research projects and record a video of some of the lab ...",""],
["http://techlav.ncat.edu/Opportunities.html","Opportunities - TECHLAV","Graduate Students PhD and MS positions are available at TECHLAV Center! Qualifications: Recent B.S. in related fields Demonstrated experience in a...",""],
["http://techlav.ncat.edu/techlav_family.html","TECHLAV Family - TECHLAV","Department of Defense (DoD) Website: http://www.defense.gov/ About:The Department of Defense is America&#39;s oldest and largest government agency.The...",""],
["http://techlav.ncat.edu/about_us.html","About Us - TECHLAV","The Testing, Evaluation, and Control of Heterogeneous Large Scale systems of Autonomous Vehicles (TECHLAV) Center was initially funded by the DoD ...",""]];
